apiVersion: apps/v1
kind: Deployment
metadata:
  name: greensky-cobol
  namespace: greensky
  labels:
    app: greensky-cobol
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greensky-cobol
  template:
    metadata:
      labels:
        app: greensky-cobol
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: cobol-publisher
          image: registry2.palmtech.com.au/greensky-cobol:latest
          env:
            - name: MQTT_BROKER
              value: "mosquitto.barleycorn.svc.cluster.local"
            - name: MQTT_PORT
              value: "1883"
            - name: FETCH_INTERVAL
              value: "30"
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              memory: 128Mi
